// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

#ifndef REAL_TQUEUE_THREADPOOL_WORK_ITEM_H
#define REAL_TQUEUE_THREADPOOL_WORK_ITEM_H

#include "macro_utils/macro_utils.h"

#include "c_pal/tqueue_ll.h"
#include "c_pal/tqueue.h"

#include "../inc/c_pal/tqueue_threadpool_work_item.h"

#define R2(X) REGISTER_GLOBAL_MOCK_HOOK(X, real_##X);

#define REGISTER_TQUEUE_THREADPOOL_WORK_ITEM_GLOBAL_MOCK_HOOK() \
    REGISTER_GLOBAL_MOCK_HOOK(TQUEUE_PUSH(THANDLE(THREADPOOL_WORK_ITEM)), (void*)TQUEUE_PUSH(THANDLE(real_THREADPOOL_WORK_ITEM))) \
    REGISTER_GLOBAL_MOCK_HOOK(TQUEUE_POP(THANDLE(THREADPOOL_WORK_ITEM)), (void*)TQUEUE_POP(THANDLE(real_THREADPOOL_WORK_ITEM))) \
    REGISTER_GLOBAL_MOCK_HOOK(TQUEUE_CREATE(THANDLE(THREADPOOL_WORK_ITEM)), (void*)TQUEUE_CREATE(THANDLE(real_THREADPOOL_WORK_ITEM))) \
    REGISTER_GLOBAL_MOCK_HOOK(TQUEUE_MOVE(THANDLE(THREADPOOL_WORK_ITEM)), (void*)TQUEUE_MOVE(THANDLE(real_THREADPOOL_WORK_ITEM))) \
    REGISTER_GLOBAL_MOCK_HOOK(TQUEUE_INITIALIZE(THANDLE(THREADPOOL_WORK_ITEM)), (void*)TQUEUE_INITIALIZE(THANDLE(real_THREADPOOL_WORK_ITEM))) \
    REGISTER_GLOBAL_MOCK_HOOK(TQUEUE_INITIALIZE_MOVE(THANDLE(THREADPOOL_WORK_ITEM)), (void*)TQUEUE_INITIALIZE_MOVE(THANDLE(real_THREADPOOL_WORK_ITEM))) \
    REGISTER_GLOBAL_MOCK_HOOK(TQUEUE_ASSIGN(THANDLE(THREADPOOL_WORK_ITEM)), (void*)TQUEUE_ASSIGN(THANDLE(real_THREADPOOL_WORK_ITEM))) \

#include "umock_c/umock_c_prod.h"

typedef THREADPOOL_WORK_ITEM real_THREADPOOL_WORK_ITEM;

THANDLE_TYPE_DECLARE(real_THREADPOOL_WORK_ITEM);
TQUEUE_DEFINE_STRUCT_TYPE(THANDLE(real_THREADPOOL_WORK_ITEM));

THANDLE_TYPE_DECLARE(TQUEUE_TYPEDEF_NAME(THANDLE(real_THREADPOOL_WORK_ITEM)));
TQUEUE_TYPE_DECLARE(THANDLE(real_THREADPOOL_WORK_ITEM));

//TQUEUE_LL_TYPE_DECLARE(TQUEUE_TYPEDEF_NAME(THANDLE(THREADPOOL_WORK_ITEM)), TQUEUE_TYPEDEF_NAME(THANDLE(real_THREADPOOL_WORK_ITEM)));

#endif // REAL_TQUEUE_THREADPOOL_WORK_ITEM_H
