// Copyright (c) Microsoft. All rights reserved.

#include "windows.h"

#pragma warning(disable: 4273)

#define CreateThreadpoolWork mocked_CreateThreadpoolWork
#define CreateThreadpoolTimer mocked_CreateThreadpoolTimer
#define InitializeThreadpoolEnvironment mocked_InitializeThreadpoolEnvironment
#define SetThreadpoolCallbackPool mocked_SetThreadpoolCallbackPool
#define CreateThreadpoolCleanupGroup mocked_CreateThreadpoolCleanupGroup
#define SetThreadpoolCallbackCleanupGroup mocked_SetThreadpoolCallbackCleanupGroup
#define CloseThreadpoolCleanupGroupMembers mocked_CloseThreadpoolCleanupGroupMembers
#define CloseThreadpoolWork mocked_CloseThreadpoolWork
#define CloseThreadpoolTimer mocked_CloseThreadpoolTimer
#define CloseThreadpoolCleanupGroup mocked_CloseThreadpoolCleanupGroup
#define DestroyThreadpoolEnvironment mocked_DestroyThreadpoolEnvironment
#define SubmitThreadpoolWork mocked_SubmitThreadpoolWork
#define SetThreadpoolTimer mocked_SetThreadpoolTimer
#define WaitForThreadpoolTimerCallbacks mocked_WaitForThreadpoolTimerCallbacks

PTP_WORK mocked_CreateThreadpoolWork(PTP_WORK_CALLBACK pfnwk, PVOID pv, PTP_CALLBACK_ENVIRON pcbe);
PTP_TIMER mocked_CreateThreadpoolTimer(PTP_TIMER_CALLBACK pfnti, PVOID pv, PTP_CALLBACK_ENVIRON pcbe);
void mocked_InitializeThreadpoolEnvironment(PTP_CALLBACK_ENVIRON pcbe);
void mocked_SetThreadpoolCallbackPool(PTP_CALLBACK_ENVIRON pcbe, PTP_POOL ptpp);
PTP_CLEANUP_GROUP mocked_CreateThreadpoolCleanupGroup(void);
VOID mocked_SetThreadpoolCallbackCleanupGroup(PTP_CALLBACK_ENVIRON pcbe, PTP_CLEANUP_GROUP ptpcg, PTP_CLEANUP_GROUP_CANCEL_CALLBACK pfng);
void mocked_CloseThreadpoolCleanupGroupMembers(PTP_CLEANUP_GROUP ptpcg, BOOL fCancelPendingCallbacks, PVOID pvCleanupContext);
void mocked_CloseThreadpoolWork(PTP_WORK pwk);
void mocked_CloseThreadpoolTimer(PTP_TIMER pti);
void mocked_CloseThreadpoolCleanupGroup(PTP_CLEANUP_GROUP ptpcg);
void mocked_DestroyThreadpoolEnvironment(PTP_CALLBACK_ENVIRON pcbe);
void mocked_SubmitThreadpoolWork(PTP_WORK pwk);
void mocked_SetThreadpoolTimer(PTP_TIMER pti, PFILETIME pftDueTime, DWORD msPeriod, DWORD msWindowLength);
void mocked_WaitForThreadpoolTimerCallbacks(PTP_TIMER pti, BOOL fCancelPendingCallbacks);

#include "../../src/threadpool_win32.c"
